#include "Vace3_generation_feedback_chain.h"
#include "verilated.h"
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
static uint64_t cycles=0;static void tick(Vace3_generation_feedback_chain*t){t->clk_i=0;t->eval();t->clk_i=1;t->eval();++cycles;}
static std::map<std::string,std::string> cfg(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open config");std::map<std::string,std::string>r;std::string s;while(std::getline(f,s)){auto n=s.find('=');if(n==std::string::npos||r.count(s.substr(0,n)))throw std::runtime_error("bad config");r[s.substr(0,n)]=s.substr(n+1);}return r;}
static void wide(uint32_t*out,const std::string&h){if(h.size()!=64)throw std::runtime_error("bad digest");for(int i=0;i<8;i++)out[i]=std::stoul(h.substr(56-i*8,8),nullptr,16);}static bool wide_eq(const uint32_t*v,const std::string&h){for(int i=0;i<8;i++)if(v[i]!=std::stoul(h.substr(56-i*8,8),nullptr,16))return false;return true;}
static void terminal(const std::string&p,bool natural,int code,uint64_t hidden,uint64_t vocab,uint64_t weights,uint64_t logits,uint64_t top,uint64_t selected,uint64_t feedback,uint64_t commits){std::ofstream f(p,std::ios::trunc);f<<"schema=ace3-generation-feedback-terminal-v1\nnatural_terminal="<<(natural?1:0)<<"\nexit_code="<<code<<"\nhidden="<<hidden<<"\nvocab="<<vocab<<"\nweights="<<weights<<"\nlogits="<<logits<<"\ntop="<<top<<"\nselected="<<selected<<"\nfeedback="<<feedback<<"\ncommits="<<commits<<"\n";f.flush();}
int main(int argc,char**argv){Verilated::commandArgs(argc,argv);std::map<std::string,std::string>a;for(int i=1;i+1<argc;i+=2)a[argv[i]]=argv[i+1];for(auto n:{"--checkpoint","--config","--hidden","--raw","--terminal"})if(!a.count(n)){std::cerr<<"missing "<<n<<"\n";return 2;}uint64_t hc=0,V=0,wc=0,lc=0,tc=0,sc=0,fc=0,cc=0;std::ofstream raw(a["--raw"],std::ios::trunc);
 try{auto c=cfg(a["--config"]);uint64_t H=std::stoull(c.at("hidden_size"));V=std::stoull(c.at("vocab_size"));uint64_t inject=a.count("--inject-after-feedback")?std::stoull(a.at("--inject-after-feedback")):0;std::ifstream hf(a["--hidden"]);std::string line;auto*hidden=new uint16_t[H];while(hc<H&&std::getline(hf,line))hidden[hc++]=std::stoul(line,nullptr,16);if(hc!=H||std::getline(hf,line))throw std::runtime_error("hidden count");int fd=open(a["--checkpoint"].c_str(),O_RDONLY);struct stat st{};if(fd<0||fstat(fd,&st)||uint64_t(st.st_size)!=std::stoull(c.at("checkpoint_bytes")))throw std::runtime_error("checkpoint size");void*mapping=mmap(nullptr,st.st_size,PROT_READ,MAP_PRIVATE,fd,0);if(mapping==MAP_FAILED)throw std::runtime_error("mmap");auto*map=static_cast<const uint8_t*>(mapping);uint64_t off=std::stoull(c.at("weight_offset")),bytes=std::stoull(c.at("weight_bytes"));if(off+bytes>uint64_t(st.st_size)||bytes!=H*V*2)throw std::runtime_error("weight range");auto*weights=map+off;
  auto*t=new Vace3_generation_feedback_chain;t->clear_i=0;t->start_valid_i=0;t->hidden_valid_i=0;t->weight_valid_i=0;t->logit_ready_i=0;t->selected_ready_i=0;t->embedding_request_ready_i=0;t->embedding_valid_i=0;t->next_input_ready_i=0;t->commit_ready_i=0;wide(t->checkpoint_sha256_i,c.at("checkpoint_sha256"));wide(t->vocabulary_sha256_i,c.at("vocabulary_sha256"));wide(t->tokenizer_config_sha256_i,c.at("tokenizer_config_sha256"));wide(t->trusted_state_tip_i,c.at("trusted_state_tip"));wide(t->presented_state_tip_i,c.at("presented_state_tip"));t->prior_position_i=std::stoul(c.at("prior_position"));t->next_position_i=std::stoul(c.at("next_position"));t->rst_ni=0;tick(t);tick(t);t->rst_ni=1;tick(t);if(!t->start_ready_o)throw std::runtime_error("start not ready");t->start_valid_i=1;tick(t);t->start_valid_i=0;
  for(uint64_t i=0;i<H;i++){t->hidden_valid_i=1;t->hidden_index_i=i;t->hidden_f16_i=hidden[i];t->hidden_last_i=(i+1==H);t->hidden_end_i=t->hidden_last_i;t->eval();if(!t->hidden_ready_o)throw std::runtime_error("hidden not ready");tick(t);}t->hidden_valid_i=0;t->hidden_end_i=0;
  for(uint64_t token=0;token<V;token++)for(uint64_t feature=0;feature<H;feature++){uint64_t index=token*H+feature;t->weight_valid_i=1;t->weight_token_index_i=token;t->weight_feature_index_i=feature;t->weight_f16_i=uint16_t(weights[index*2])|(uint16_t(weights[index*2+1])<<8);t->weight_last_feature_i=(feature+1==H);t->weight_last_token_i=(token+1==V&&feature+1==H);t->weight_end_i=t->weight_last_token_i;t->eval();if(!t->weight_ready_o)throw std::runtime_error("weight not ready");tick(t);wc++;if(feature+1==H){t->weight_valid_i=0;t->weight_end_i=0;t->logit_ready_i=1;t->eval();if(!t->logit_valid_o||t->logit_token_index_o!=token)throw std::runtime_error("logit framing");tick(t);lc++;t->logit_ready_i=0;}}
  for(int wait=0;wait<100&&!t->selected_valid_o;wait++){t->eval();if(t->error_valid_o)throw std::runtime_error("RTL error before selection");tick(t);}if(!t->selected_valid_o)throw std::runtime_error("missing RTL selection");uint32_t selected=t->selected_token_index_o;uint16_t selected_logit=t->selected_logit_f16_o;raw<<"selected "<<selected<<" "<<std::hex<<std::setw(4)<<std::setfill('0')<<selected_logit<<std::dec<<"\n";raw.flush();sc=1;t->selected_ready_i=1;tick(t);t->selected_ready_i=0;
  for(int wait=0;wait<30&&!t->embedding_request_valid_o;wait++)tick(t);if(!t->embedding_request_valid_o||t->embedding_request_token_index_o!=selected)throw std::runtime_error("embedding request mismatch");tc=std::stoull(c.at("top_k"));t->embedding_request_ready_i=1;tick(t);t->embedding_request_ready_i=0;
  uint64_t accepted=0;while(fc<H){t->embedding_valid_i=accepted<H;t->embedding_token_index_i=selected;t->embedding_feature_index_i=accepted;uint64_t index=uint64_t(selected)*H+(accepted<H?accepted:H-1);t->embedding_f16_i=uint16_t(weights[index*2])|(uint16_t(weights[index*2+1])<<8);t->embedding_last_i=(accepted+1==H);t->embedding_end_i=t->embedding_last_i;t->next_input_ready_i=((cycles%7)!=3);t->eval();bool in=t->embedding_valid_i&&t->embedding_ready_o;bool out=t->next_input_valid_o&&t->next_input_ready_i;if(out){if(t->next_input_token_index_o!=selected||t->next_input_feature_index_o!=fc||t->next_input_position_o!=std::stoul(c.at("next_position")))throw std::runtime_error("feedback framing");raw<<"feedback "<<fc<<" "<<std::hex<<std::setw(4)<<std::setfill('0')<<uint16_t(t->next_input_f16_o)<<std::dec<<"\n";raw.flush();fc++;}tick(t);if(in)accepted++;if(inject&&out&&fc==inject)throw std::runtime_error("injected failure after durable feedback write");if(t->error_valid_o)throw std::runtime_error("RTL feedback error");}
  t->embedding_valid_i=0;t->embedding_end_i=0;t->next_input_ready_i=1;for(int wait=0;wait<20&&!t->commit_valid_o;wait++)tick(t);if(!t->commit_valid_o||t->commit_token_index_o!=selected||t->commit_position_o!=std::stoul(c.at("next_position"))||!wide_eq(t->commit_prior_state_tip_o,c.at("trusted_state_tip")))throw std::runtime_error("commit mismatch");raw<<"commit "<<selected<<" "<<t->commit_position_o<<" "<<c.at("trusted_state_tip")<<"\n";raw.flush();cc=1;t->commit_ready_i=1;tick(t);terminal(a["--terminal"],true,0,hc,V,wc,lc,tc,sc,fc,cc);std::cout<<"GENERATION_FEEDBACK_RTL_TERMINAL hidden="<<hc<<" vocab="<<V<<" token="<<selected<<" feedback="<<fc<<" cycles="<<cycles<<"\n";munmap(mapping,st.st_size);close(fd);delete[]hidden;delete t;return 0;
 }catch(const std::exception&e){terminal(a["--terminal"],false,1,hc,V,wc,lc,tc,sc,fc,cc);std::cerr<<e.what()<<"\n";return 1;}}
