`timescale 1ns/1ps
`default_nettype none

module ace3_qkv_rope_cache_verilator_top (
    input  wire        clk_i,
    input  wire        rst_ni,
    input  wire        clear_i,
    input  wire        rope_in_valid_i,
    output wire        rope_in_ready_o,
    input  wire        rope_is_key_i,
    input  wire [3:0]  rope_head_i,
    input  wire [4:0]  rope_pair_i,
    input  wire [14:0] rope_position_i,
    input  wire [15:0] rope_low_i,
    input  wire [15:0] rope_high_i,
    input  wire [15:0] rope_cos_i,
    input  wire [15:0] rope_sin_i,
    output wire        rope_out_valid_o,
    input  wire        rope_out_ready_i,
    output wire        rope_out_is_key_o,
    output wire [3:0]  rope_out_head_o,
    output wire [4:0]  rope_out_pair_o,
    output wire [14:0] rope_out_position_o,
    output wire [15:0] rope_out_low_o,
    output wire [15:0] rope_out_high_o,
    output wire        rope_invalid_o,
    output wire        rope_saturation_o,
    input  wire        cache_write_valid_i,
    output wire        cache_write_ready_o,
    input  wire [1:0]  cache_write_slot_i,
    input  wire [14:0] cache_write_position_i,
    input  wire [3:0]  cache_write_head_i,
    input  wire [5:0]  cache_write_dimension_i,
    input  wire [15:0] cache_write_k_i,
    input  wire [15:0] cache_write_v_i,
    input  wire        cache_read_valid_i,
    output wire        cache_read_ready_o,
    input  wire [1:0]  cache_read_slot_i,
    input  wire [14:0] cache_read_position_i,
    input  wire [3:0]  cache_read_head_i,
    input  wire [5:0]  cache_read_dimension_i,
    output wire        cache_out_valid_o,
    input  wire        cache_out_ready_i,
    output wire        cache_out_hit_o,
    output wire [1:0]  cache_out_slot_o,
    output wire [14:0] cache_out_position_o,
    output wire [3:0]  cache_out_head_o,
    output wire [5:0]  cache_out_dimension_o,
    output wire [15:0] cache_out_k_o,
    output wire [15:0] cache_out_v_o
);
    ace3_qwen2_rope_pair rope (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .clear_i(clear_i),
        .in_valid_i(rope_in_valid_i),
        .in_ready_o(rope_in_ready_o),
        .is_key_i(rope_is_key_i),
        .head_index_i(rope_head_i),
        .pair_index_i(rope_pair_i),
        .position_i(rope_position_i),
        .low_f16_i(rope_low_i),
        .high_f16_i(rope_high_i),
        .cos_f16_i(rope_cos_i),
        .sin_f16_i(rope_sin_i),
        .out_valid_o(rope_out_valid_o),
        .out_ready_i(rope_out_ready_i),
        .is_key_o(rope_out_is_key_o),
        .head_index_o(rope_out_head_o),
        .pair_index_o(rope_out_pair_o),
        .position_o(rope_out_position_o),
        .low_f16_o(rope_out_low_o),
        .high_f16_o(rope_out_high_o),
        .invalid_operand_o(rope_invalid_o),
        .saturation_o(rope_saturation_o)
    );

    ace3_fp16_kv_cache #(
        .CACHE_SLOTS(2),
        .MAX_TOKENS(8),
        .KV_HEADS(2),
        .HEAD_DIM(64)
    ) cache (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .clear_i(clear_i),
        .write_valid_i(cache_write_valid_i),
        .write_ready_o(cache_write_ready_o),
        .write_cache_slot_i(cache_write_slot_i),
        .write_position_i(cache_write_position_i),
        .write_head_i(cache_write_head_i),
        .write_dimension_i(cache_write_dimension_i),
        .write_k_f16_i(cache_write_k_i),
        .write_v_f16_i(cache_write_v_i),
        .read_valid_i(cache_read_valid_i),
        .read_ready_o(cache_read_ready_o),
        .read_cache_slot_i(cache_read_slot_i),
        .read_position_i(cache_read_position_i),
        .read_head_i(cache_read_head_i),
        .read_dimension_i(cache_read_dimension_i),
        .out_valid_o(cache_out_valid_o),
        .out_ready_i(cache_out_ready_i),
        .out_hit_o(cache_out_hit_o),
        .out_cache_slot_o(cache_out_slot_o),
        .out_position_o(cache_out_position_o),
        .out_head_o(cache_out_head_o),
        .out_dimension_o(cache_out_dimension_o),
        .out_k_f16_o(cache_out_k_o),
        .out_v_f16_o(cache_out_v_o)
    );
endmodule

`default_nettype wire
