`timescale 1ns/1ps
`default_nettype none

module ace3_attention_verilator_top (
    input  wire        clk_i,
    input  wire        rst_ni,
    input  wire        clear_i,

    input  wire        score_start_valid_i,
    output wire        score_start_ready_o,
    input  wire [3:0]  score_query_head_i,
    input  wire [3:0]  score_key_head_i,
    input  wire [14:0] score_query_position_i,
    input  wire [14:0] score_key_position_i,
    input  wire        score_pair_valid_i,
    output wire        score_pair_ready_o,
    input  wire [15:0] score_q_f16_i,
    input  wire [15:0] score_k_f16_i,
    input  wire        score_cache_hit_i,
    output wire        score_out_valid_o,
    input  wire        score_out_ready_i,
    output wire [15:0] score_f16_o,
    output wire [3:0]  score_query_head_o,
    output wire [3:0]  score_key_head_o,
    output wire [14:0] score_query_position_o,
    output wire [14:0] score_key_position_o,
    output wire        score_causal_o,
    output wire        score_cache_miss_o,
    output wire        score_invalid_o,
    output wire        score_saturation_o,
    output wire        score_busy_o,

    input  wire        softmax_start_valid_i,
    output wire        softmax_start_ready_o,
    input  wire [3:0]  softmax_query_head_i,
    input  wire [14:0] softmax_query_position_i,
    input  wire [15:0] softmax_context_count_i,
    input  wire        softmax_score_valid_i,
    output wire        softmax_score_ready_o,
    input  wire [15:0] softmax_score_f16_i,
    input  wire [14:0] softmax_key_position_i,
    input  wire        softmax_causal_i,
    input  wire        softmax_cache_miss_i,
    input  wire        softmax_invalid_i,
    output wire        softmax_out_valid_o,
    input  wire        softmax_out_ready_i,
    output wire [15:0] softmax_probability_f16_o,
    output wire [3:0]  softmax_query_head_o,
    output wire [14:0] softmax_query_position_o,
    output wire [14:0] softmax_key_position_o,
    output wire [15:0] softmax_index_o,
    output wire        softmax_last_o,
    output wire        softmax_row_error_o,
    output wire        softmax_out_cache_miss_o,
    output wire        softmax_out_invalid_o,
    output wire        softmax_busy_o,

    input  wire        value_start_valid_i,
    output wire        value_start_ready_o,
    input  wire [3:0]  value_query_head_i,
    input  wire [3:0]  value_head_i,
    input  wire [14:0] value_query_position_i,
    input  wire [5:0]  value_dimension_i,
    input  wire [15:0] value_context_count_i,
    input  wire        value_term_valid_i,
    output wire        value_term_ready_o,
    input  wire [15:0] value_probability_f16_i,
    input  wire [15:0] value_cached_f16_i,
    input  wire        value_hit_i,
    input  wire        value_row_error_i,
    output wire        value_out_valid_o,
    input  wire        value_out_ready_i,
    output wire [15:0] value_f16_o,
    output wire [3:0]  value_query_head_o,
    output wire [3:0]  value_head_o,
    output wire [14:0] value_query_position_o,
    output wire [5:0]  value_dimension_o,
    output wire        value_row_error_o,
    output wire        value_cache_miss_o,
    output wire        value_invalid_o,
    output wire        value_saturation_o,
    output wire        value_busy_o
);
    ace3_attention_score_core score_core (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .clear_i(clear_i),
        .start_valid_i(score_start_valid_i),
        .start_ready_o(score_start_ready_o),
        .query_head_i(score_query_head_i),
        .key_head_i(score_key_head_i),
        .query_position_i(score_query_position_i),
        .key_position_i(score_key_position_i),
        .pair_valid_i(score_pair_valid_i),
        .pair_ready_o(score_pair_ready_o),
        .q_f16_i(score_q_f16_i),
        .k_f16_i(score_k_f16_i),
        .cache_hit_i(score_cache_hit_i),
        .out_valid_o(score_out_valid_o),
        .out_ready_i(score_out_ready_i),
        .score_f16_o(score_f16_o),
        .query_head_o(score_query_head_o),
        .key_head_o(score_key_head_o),
        .query_position_o(score_query_position_o),
        .key_position_o(score_key_position_o),
        .causal_o(score_causal_o),
        .cache_miss_o(score_cache_miss_o),
        .invalid_operand_o(score_invalid_o),
        .saturation_o(score_saturation_o),
        .busy_o(score_busy_o)
    );

    ace3_attention_softmax_core #(
        .CONTEXT_MAX(16)
    ) softmax_core (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .clear_i(clear_i),
        .start_valid_i(softmax_start_valid_i),
        .start_ready_o(softmax_start_ready_o),
        .query_head_i(softmax_query_head_i),
        .query_position_i(softmax_query_position_i),
        .context_count_i(softmax_context_count_i),
        .score_valid_i(softmax_score_valid_i),
        .score_ready_o(softmax_score_ready_o),
        .score_f16_i(softmax_score_f16_i),
        .key_position_i(softmax_key_position_i),
        .causal_i(softmax_causal_i),
        .cache_miss_i(softmax_cache_miss_i),
        .invalid_operand_i(softmax_invalid_i),
        .out_valid_o(softmax_out_valid_o),
        .out_ready_i(softmax_out_ready_i),
        .probability_f16_o(softmax_probability_f16_o),
        .query_head_o(softmax_query_head_o),
        .query_position_o(softmax_query_position_o),
        .key_position_o(softmax_key_position_o),
        .out_index_o(softmax_index_o),
        .out_last_o(softmax_last_o),
        .row_error_o(softmax_row_error_o),
        .cache_miss_o(softmax_out_cache_miss_o),
        .invalid_operand_o(softmax_out_invalid_o),
        .busy_o(softmax_busy_o)
    );

    ace3_attention_value_core #(
        .CONTEXT_MAX(16)
    ) value_core (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .clear_i(clear_i),
        .start_valid_i(value_start_valid_i),
        .start_ready_o(value_start_ready_o),
        .query_head_i(value_query_head_i),
        .value_head_i(value_head_i),
        .query_position_i(value_query_position_i),
        .dimension_i(value_dimension_i),
        .context_count_i(value_context_count_i),
        .term_valid_i(value_term_valid_i),
        .term_ready_o(value_term_ready_o),
        .probability_f16_i(value_probability_f16_i),
        .value_f16_i(value_cached_f16_i),
        .value_hit_i(value_hit_i),
        .row_error_i(value_row_error_i),
        .out_valid_o(value_out_valid_o),
        .out_ready_i(value_out_ready_i),
        .value_f16_o(value_f16_o),
        .query_head_o(value_query_head_o),
        .value_head_o(value_head_o),
        .query_position_o(value_query_position_o),
        .dimension_o(value_dimension_o),
        .row_error_o(value_row_error_o),
        .cache_miss_o(value_cache_miss_o),
        .invalid_operand_o(value_invalid_o),
        .saturation_o(value_saturation_o),
        .busy_o(value_busy_o)
    );
endmodule

`default_nettype wire
