`timescale 1ns/1ps
`default_nettype none
module ace3_generation_feedback_chain_tb;
 localparam [255:0] CK=256'h1,VO=256'h2,TC=256'h3,TIP=256'h4;
 reg clk=0,rst_n=0,clear=0,start_valid=0;wire start_ready;reg [255:0] ck=CK,vo=VO,tc=TC,trusted=TIP,presented=TIP;reg [31:0] prior_position=0,next_position=1;
 reg hidden_valid=0,hidden_last=0,hidden_end=0;wire hidden_ready;reg [1:0] hidden_index=0;reg [15:0] hidden_f16=0;
 reg weight_valid=0,weight_last_feature=0,weight_last_token=0,weight_end=0;wire weight_ready;reg [2:0] weight_token=0;reg [1:0] weight_feature=0;reg [15:0] weight_f16=0;
 wire logit_valid;reg logit_ready=1;wire [2:0] logit_token;wire [15:0] logit_f16;wire selected_valid;reg selected_ready=0;wire [2:0] selected_token;wire [15:0] selected_logit;
 wire request_valid;reg request_ready=0;wire [2:0] request_token;reg embedding_valid=0,embedding_last=0,embedding_end=0;wire embedding_ready;reg [2:0] embedding_token=0;reg [1:0] embedding_feature=0;reg [15:0] embedding_f16=0;
 wire next_valid;reg next_ready=0;wire [2:0] next_token;wire [1:0] next_feature;wire [15:0] next_f16;wire next_last;wire [31:0] next_pos;wire commit_valid;reg commit_ready=0;wire [2:0] commit_token;wire [31:0] commit_pos;wire [255:0] commit_tip;wire error_valid;wire [3:0] error_code;wire invalid,saturation,busy;integer failures=0,malformed=0;
 ace3_generation_feedback_chain #(.HIDDEN_SIZE(4),.VOCAB_SIZE(5),.TOP_K(3),.TOKEN_INDEX_WIDTH(3),.FEATURE_INDEX_WIDTH(2),.TOP_RANK_WIDTH(2),.EXPECTED_CHECKPOINT_SHA256(CK),.EXPECTED_VOCABULARY_SHA256(VO),.EXPECTED_TOKENIZER_CONFIG_SHA256(TC)) dut(
 .clk_i(clk),.rst_ni(rst_n),.clear_i(clear),.start_valid_i(start_valid),.start_ready_o(start_ready),.checkpoint_sha256_i(ck),.vocabulary_sha256_i(vo),.tokenizer_config_sha256_i(tc),.trusted_state_tip_i(trusted),.presented_state_tip_i(presented),.prior_position_i(prior_position),.next_position_i(next_position),
 .hidden_valid_i(hidden_valid),.hidden_ready_o(hidden_ready),.hidden_index_i(hidden_index),.hidden_f16_i(hidden_f16),.hidden_last_i(hidden_last),.hidden_end_i(hidden_end),.weight_valid_i(weight_valid),.weight_ready_o(weight_ready),.weight_token_index_i(weight_token),.weight_feature_index_i(weight_feature),.weight_f16_i(weight_f16),.weight_last_feature_i(weight_last_feature),.weight_last_token_i(weight_last_token),.weight_end_i(weight_end),
 .logit_valid_o(logit_valid),.logit_ready_i(logit_ready),.logit_token_index_o(logit_token),.logit_f16_o(logit_f16),.selected_valid_o(selected_valid),.selected_ready_i(selected_ready),.selected_token_index_o(selected_token),.selected_logit_f16_o(selected_logit),.embedding_request_valid_o(request_valid),.embedding_request_ready_i(request_ready),.embedding_request_token_index_o(request_token),
 .embedding_valid_i(embedding_valid),.embedding_ready_o(embedding_ready),.embedding_token_index_i(embedding_token),.embedding_feature_index_i(embedding_feature),.embedding_f16_i(embedding_f16),.embedding_last_i(embedding_last),.embedding_end_i(embedding_end),.next_input_valid_o(next_valid),.next_input_ready_i(next_ready),.next_input_token_index_o(next_token),.next_input_feature_index_o(next_feature),.next_input_f16_o(next_f16),.next_input_last_o(next_last),.next_input_position_o(next_pos),.commit_valid_o(commit_valid),.commit_ready_i(commit_ready),.commit_token_index_o(commit_token),.commit_position_o(commit_pos),.commit_prior_state_tip_o(commit_tip),.error_valid_o(error_valid),.error_code_o(error_code),.invalid_operand_o(invalid),.saturation_o(saturation),.busy_o(busy));
 always #5 clk=~clk;
 task pulse_clear;begin @(negedge clk);clear=1;@(posedge clk);@(negedge clk);clear=0;end endtask
 task start;begin @(negedge clk);start_valid=1;if(start_ready!==1)failures=failures+1;@(posedge clk);@(negedge clk);start_valid=0;end endtask
 task hidden(input [1:0] i);begin @(negedge clk);hidden_index=i;hidden_f16=16'h3c00;hidden_last=(i==3);hidden_end=(i==3);hidden_valid=1;@(posedge clk);@(negedge clk);hidden_valid=0;hidden_end=0;end endtask
 function [15:0] w(input [2:0] t,input [1:0] f);begin if(f!=0)w=0;else case(t)0:w=16'h3c00;1:w=16'h3c00;2:w=16'h3800;3:w=0;default:w=16'hbc00;endcase end endfunction
 task weights;integer t,f;begin for(t=0;t<5;t=t+1)for(f=0;f<4;f=f+1)begin @(negedge clk);weight_token=t;weight_feature=f;weight_f16=w(t,f);weight_last_feature=(f==3);weight_last_token=(t==4&&f==3);weight_end=weight_last_token;weight_valid=1;@(posedge clk);@(negedge clk);weight_valid=0;weight_end=0;if(f==3)begin wait(logit_valid===1);@(posedge clk);end end end endtask
 task reach_request;integer i;begin start;for(i=0;i<4;i=i+1)hidden(i);weights;wait(selected_valid===1);if(selected_token!==0)begin $display("TIE_SELECT_FAIL token=%0d",selected_token);failures=failures+1;end @(negedge clk);selected_ready=1;@(posedge clk);@(negedge clk);selected_ready=0;wait(request_valid===1);if(request_token!==0)failures=failures+1;request_ready=1;@(posedge clk);@(negedge clk);request_ready=0;end endtask
 task send_embedding(input [2:0] token,input [1:0] feature,input [15:0] bits,input last);begin @(negedge clk);embedding_token=token;embedding_feature=feature;embedding_f16=bits;embedding_last=last;embedding_end=last;embedding_valid=1;while(embedding_ready!==1)@(negedge clk);@(posedge clk);@(negedge clk);embedding_valid=0;embedding_end=0;end endtask
 initial begin repeat(3)@(posedge clk);rst_n=1;repeat(2)@(posedge clk);
  reach_request;next_ready=1;send_embedding(0,0,16'h3c00,0);next_ready=0;send_embedding(0,1,16'h4000,0);repeat(2)begin @(posedge clk);if(next_valid!==1||next_feature!==1||next_f16!==16'h4000)failures=failures+1;end next_ready=1;send_embedding(0,2,16'h4200,0);send_embedding(0,3,16'h4400,1);wait(commit_valid===1);if(commit_token!==0||commit_pos!==1||commit_tip!==TIP)failures=failures+1;commit_ready=1;@(posedge clk);commit_ready=0;pulse_clear;
  presented=256'h5;start;wait(error_valid===1);if(error_code!==2)failures=failures+1;malformed=malformed+1;pulse_clear;presented=TIP;
  reach_request;next_ready=1;send_embedding(1,0,16'h3c00,0);wait(error_valid===1);if(error_code!==4)failures=failures+1;malformed=malformed+1;pulse_clear;
  reach_request;next_ready=1;send_embedding(0,1,16'h3c00,0);wait(error_valid===1);if(error_code!==5)failures=failures+1;malformed=malformed+1;pulse_clear;
  if(failures==0)$display("GENERATION_FEEDBACK_PROTOCOL_PASS tie=ascending_token backpressure=pass malformed=%0d",malformed);else $fatal(1,"GENERATION_FEEDBACK_PROTOCOL_FAIL failures=%0d",failures);$finish;end
endmodule
`default_nettype wire
