"""Synthetic custody fixtures and one guarded read-only retained-capture check.

PYTHONPATH=. PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 python3 -B \
tests/test_diagnostic_identity_custody_v1.py --validate FRESH_BUILD_ATTEMPT

The shared runner compiles sources and runs the focused non-generative suites
once. Its audit/profile guards forbid scientific/producer/service dispatch and
outside-attempt writes. Synthetic review/native records are fixtures only.

--validate-stage11 FRESH_BUILD_ATTEMPT [TRUSTED_DECLARATION_PINS ACTUAL_LAUNCH]
also exercises custody-to-authority-bundle integration. The optional JSON files
must be supplied from independent creation/review authority, not generated by
this validation. Absent proposal authority is one UNKNOWN, not permission to
infer a declaration from stage11 narratives. Custody and bundle outputs occupy
separate subdirectories of the one fresh attempt; all original inputs stay
outside it. Missing proposal authority retains explicit non-emission receipts
for the proposal, catalog, custody, bundle and decision without consulting
historical task narratives. No scientific attempt is reserved or executed.

--validate-manager-declarations FRESH_BUILD_ATTEMPT is the zero-dispatch
current-declaration interface check. It compiles the final sources, runs only
synthetic read-only interface tests and validates the fixed Manager package once.
It never calls custody emission, materialization, identity preflight or producers.
FAIL/UNKNOWN preserves the exact unavailable or inconsistent authority binding;
the package is never repaired here. Normal Host Reviewer handling is separate.
"""

from copy import deepcopy
import hashlib
import importlib.util
from io import BytesIO
import json
from datetime import datetime, timezone
from pathlib import Path
import sys

import pytest
import numpy as np

from ace3.model.candidates import diagnostic_capture_v1 as capture
from ace3.model.candidates import diagnostic_identity_custody_v1 as custody
from ace3.model.candidates import diagnostic_identity_preflight_v1 as gate


previous = sys.modules.get("test_diagnostic_identity_authority_bundle_v1")
if previous is None:
    spec = importlib.util.spec_from_file_location(
        "test_diagnostic_identity_authority_bundle_v1",
        Path(__file__).with_name("test_diagnostic_identity_authority_bundle_v1.py"))
    if spec is None or spec.loader is None:
        raise RuntimeError("shared custody test/validation module is unavailable")
    previous = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = previous
    spec.loader.exec_module(previous)


prior = previous.prior
case = previous.case


def origins_for(case):
    directory, proposal, catalog, _ = case
    declaration = {
        "schema_version": 1, "kind": "diagnostic_identity_declaration",
        "diagnostic_identity": proposal["identity"],
        **{field: proposal[field] for field in ("source_roles", "source_snapshots", "launch")}}
    terminals = {
        "schema_version": 1, "kind": "diagnostic_terminal_declarations",
        "scoped_missions": [lane["mission_id"] for lane in catalog["lanes"]],
        "lanes": [{key: value for key, value in lane.items() if key != "identity_paths"}
                  for lane in catalog["lanes"]]}
    return {"proposal": prior.put(directory, "declaration.json", declaration),
            "terminals": prior.put(directory, "terminal-declarations.json", terminals)}


def produce(case, origins=None):
    if origins is None:
        origins = origins_for(case)
    attempt = case[0] / "custody"
    reservation = capture.reserve_authentication_attempt(attempt)
    result = custody.emit_custody(origins, case[3], attempt, reservation)
    assert result["dispatch_authorized"] is False
    assert result["authority_root"] is result["scientific_or_admission_claim"] is False
    assert all(result[key] == 0 for key in
               ("scientific_invocations", "producer_invocations", "service_invocations"))
    return result, origins


def test_emits_schema_one(case):
    result, origins = produce(case)
    assert result["status"] == "PASS"
    proposal, catalog = (capture.retained_document(result[key]) for key in ("proposal", "catalog"))
    assert proposal == {key: case[1][key] for key in
                        ("schema_version", "identity", "source_roles", "source_snapshots", "launch")}
    assert catalog == {**case[2], "scoped_missions": ["synthetic-closed"]}
    assert custody.validate_custody(result["receipt"], origins, case[3],
                                    reservation=result["reservation"])["status"] == "PASS"
    assert gate.preflight_identity(result["proposal"], result["catalog"], case[3])[
        "status"] == "ACCEPTED_NOVEL"
    assert all(Path(pin["path"]).is_relative_to(case[0] / "custody")
               for pin in (result["proposal"], result["catalog"], result["receipt"]))


@pytest.mark.parametrize("variant", ["novel", "environment_order", "closed"])
def test_custody_to_authority_bundle(case, variant):
    if variant == "closed":
        lane = case[2]["lanes"][0]
        run = capture.retained_document(lane["capture"]["receipt"])
        case[1]["identity"] = capture.retained_document(run["results"][0]["files"][3])[
            "diagnostic_identity"]
    result, origins = produce(case)
    if variant == "environment_order":
        launch = case[3]
        launch["environment"] = dict(reversed(list(launch["environment"].items())))
        launch["command"] = capture.environment_command(launch["environment"], launch["argv"])
    bundle_origins = custody.authority_bundle_origins(
        result["receipt"], origins, case[3], reservation=result["reservation"])
    attempt = case[0] / "authority"
    reservation = capture.reserve_authentication_attempt(attempt)
    emitted = previous.bundle.materialize(bundle_origins, case[3], attempt, reservation)
    independently_derived = custody.authority_bundle_origins(
        result["receipt"], origins, case[3], reservation=result["reservation"])
    checked = previous.bundle.validate_bundle(
        emitted["receipt"], independently_derived, case[3], reservation=reservation)
    expected = "REJECTED" if variant == "closed" else "PASS"
    assert emitted["status"] == checked["status"] == expected
    assert checked["identity_preflight"]["status"] == (
        "REJECTED" if variant == "closed" else "ACCEPTED_NOVEL")
    if variant == "closed":
        assert checked["reason"] == "closed_equivalent"
    previous.assert_no_dispatch(checked)


@pytest.mark.parametrize("mutation", ["roots", "reservation", "receipt", "missing_receipt"])
def test_bundle_selectors_require_independent_custody(case, mutation):
    result, origins = produce(case)
    reservation = result["reservation"]
    if mutation == "roots":
        origins = {**origins, "proposal": result["proposal"]}
    elif mutation == "reservation":
        reservation = None
    elif mutation == "receipt":
        receipt = capture.retained_document(result["receipt"])
        receipt["service_invocations"] = 1
        result["receipt"] = prior.put(case[0] / "custody", "forged.json", receipt)
    else:
        Path(result["receipt"]["path"]).unlink()
    error = capture.UnavailableBinding if mutation == "missing_receipt" else RuntimeError
    with pytest.raises(error):
        custody.authority_bundle_origins(
            result["receipt"], origins, case[3], reservation=reservation)


def test_custody_pass_does_not_claim_novelty(case):
    lane = case[2]["lanes"][0]
    run = capture.retained_document(lane["capture"]["receipt"])
    case[1]["identity"] = capture.retained_document(run["results"][0]["files"][3])[
        "diagnostic_identity"]
    result, _ = produce(case)
    assert result["status"] == "PASS"
    assert gate.preflight_identity(result["proposal"], result["catalog"], case[3])[
        "reason"] == "closed_equivalent"


def test_environment_order_only(case):
    origins = origins_for(case)
    launch = case[3]
    launch["environment"] = dict(reversed(list(launch["environment"].items())))
    launch["command"] = capture.environment_command(launch["environment"], launch["argv"])
    result, _ = produce(case, origins)
    assert result["status"] == "PASS"
    assert custody.validate_custody(result["receipt"], origins, launch,
                                    reservation=result["reservation"])["status"] == "PASS"


@pytest.mark.parametrize("mutation", ["value", "argv", "duplicate", "extra", "missing",
                                    "uid", "cwd", "role", "model", "access", "budget", "quoting"])
def test_launch_mutations_rejected(case, mutation):
    origins = origins_for(case)
    launch = case[3]
    if mutation == "value":
        launch["environment"]["B"] = "changed"
    elif mutation == "argv":
        launch["argv"].append("--changed")
    elif mutation == "duplicate":
        launch["command"] = "A=one " + launch["command"]
    elif mutation == "extra":
        launch["environment"]["C"] = "extra"
    elif mutation == "missing":
        del launch["environment"]["A"]
    elif mutation == "quoting":
        launch["command"] = launch["command"].replace("A=one", "A='one'")
    else:
        launch[mutation] = "changed"
    if mutation in {"value", "argv", "extra", "missing"}:
        launch["command"] = capture.environment_command(launch["environment"], launch["argv"])
    result, _ = produce(case, origins)
    assert result["status"] == "REJECTED"
    assert not (case[0] / "custody/diagnostic_proposal.json").exists()


@pytest.mark.parametrize("which", ["proposal", "terminals"])
def test_duplicate_declaration_keys_rejected(case, which):
    origins = origins_for(case)
    origins[which] = prior.put(case[0], "duplicate.json",
                              b'{"schema_version":1,"schema_version":1}')
    result, _ = produce(case, origins)
    assert result["status"] == "REJECTED" and "duplicate" in result["reason"]


@pytest.mark.parametrize("mutation", ["missing", "conflated", "current", "historical", "snapshot"])
def test_source_roles_rejected(case, mutation):
    roles = case[1]["source_roles"]
    if mutation == "missing":
        del roles["historical_generation"]
    elif mutation == "conflated":
        roles["historical_generation"] = deepcopy(roles["current_diagnostic"])
    elif mutation == "snapshot":
        Path(roles["historical_generation"]["retained"]["path"]).unlink()
    else:
        pin = prior.put(case[0], "other-source.py", b"unrelated source bytes")
        if mutation == "current":
            roles["current_diagnostic"] = {"source": pin, "retained": pin}
        else:
            snapshot = prior.put(case[0], "other-snapshot.py", b"unrelated source bytes")
            roles["historical_generation"] = {"source": pin, "retained": snapshot}
    assert produce(case)[0]["status"] == ("UNKNOWN" if mutation == "snapshot" else "REJECTED")


@pytest.mark.parametrize("mutation", ["duplicate", "omitted", "renamed", "narrative", "schema"])
def test_terminal_scope_rejected(case, mutation):
    origins = origins_for(case)
    terminals = capture.retained_document(origins["terminals"])
    if mutation == "duplicate":
        terminals["scoped_missions"] *= 2
        terminals["lanes"] *= 2
    elif mutation == "omitted":
        terminals["lanes"] = []
    elif mutation == "renamed":
        terminals["scoped_missions"] = ["new-task-name"]
    elif mutation == "narrative":
        terminals["lanes"] = "the task and all native checks were done"
    else:
        terminals["schema_version"] = True
    origins["terminals"] = prior.put(case[0], "changed-terminals.json", terminals)
    assert produce(case, origins)[0]["status"] == "REJECTED"


def change_capture(case, mutation):
    """Build new synthetic retained bytes/review links; never edit a real capture."""
    lane = case[2]["lanes"][0]
    receipt = deepcopy(capture.retained_document(lane["capture"]["receipt"]))
    row = receipt["results"][0]
    data = [Path(pin["path"]).read_bytes() for pin in row["files"]]
    if mutation == "missing_identity":
        data[3] = capture.encoded({"task_name": "synthetic-closed", "status": "done",
                                  "narrative": "identity cannot be reconstructed"})
    elif mutation == "duplicate_identity":
        data[3] = b'{"diagnostic_identity":{},"diagnostic_identity":{}}\n'
    elif mutation == "argv":
        data[1] = capture.encoded(row["argv"] + ["--changed"])
    elif mutation == "environment":
        environment = capture.decode_retained(data[2])
        environment["environment"]["A"] = "changed"
        data[2] = capture.encoded(environment)
    elif mutation == "timeout":
        row["timed_out"] = True
    elif mutation == "exit":
        row["exit_status"] = 9
    if mutation in {"missing_identity", "duplicate_identity"}:
        data[5] = (b"COMMAND\n" + data[0] + b"ENVIRONMENT\n" + data[2] + b"\nSTDOUT\n"
                   + data[3] + b"\nSTDERR\n" + data[4] + b"\nEXIT_STATUS=0\nTIMED_OUT=False\n")
    elif mutation == "framing":
        data[5] += b"extra unframed bytes"
    directory = case[0] / "mutant-retained"
    directory.mkdir()
    row["files"] = [prior.put(directory, row["label"] + suffix, value)
                    for suffix, value in zip(capture.SUFFIXES, data, strict=True)]
    if mutation == "member_link":
        row["files"][3], row["files"][4] = row["files"][4], row["files"][3]
    receipt_pin = prior.put(directory, "capture.json", receipt)
    lane["capture"] = {**lane["capture"], "directory": str(directory), "receipt": receipt_pin}
    native = lane["native"]["pin"]
    checkpoint = prior.put(directory, "checkpoint.txt", (
        f"capture.json {receipt_pin['sha256']}\n"
        f"{Path(native['path']).name} {native['sha256']}\n").encode())
    review = capture.retained_document(lane["review"])
    review["checkpoint"] = {"path": checkpoint["path"]}
    review_pin = prior.put(directory, "review.json", review)
    latest = prior.put(directory, "latest.json", {
        "kind": "handoff_ref", "handoff": {"path": review_pin["path"]}})
    lane.update(latest=latest, review=review_pin, checkpoint=checkpoint)


@pytest.mark.parametrize("mutation", ["duplicate_identity", "argv", "environment",
                                    "timeout", "exit", "framing", "member_link"])
def test_pinned_capture_mutations_rejected(case, mutation):
    change_capture(case, mutation)
    assert produce(case)[0]["status"] == "REJECTED"


def test_missing_historical_identity_unknown(case):
    change_capture(case, "missing_identity")
    result, origins = produce(case)
    assert result["status"] == "UNKNOWN"
    assert "diagnostic_identity" in result["unavailable_binding"]
    assert "saved.stdout" in result["unavailable_binding"]
    assert not (case[0] / "custody/terminal_catalog.json").exists()
    assert custody.validate_custody(result["receipt"], origins, case[3],
                                    reservation=result["reservation"])["status"] == "UNKNOWN"


@pytest.mark.parametrize("mutation", ["latest", "review", "checkpoint", "native"])
def test_missing_review_native_binding_unknown(case, mutation):
    lane = case[2]["lanes"][0]
    pin = lane["native"]["pin"] if mutation == "native" else lane[mutation]
    Path(pin["path"]).unlink()
    result, _ = produce(case)
    assert result["status"] == "UNKNOWN" and pin["path"] in result["unavailable_binding"]


@pytest.mark.parametrize("mutation", ["origins", "source_roles", "launch", "write_audit",
                                    "producer_invocations", "service_invocations", "proposal", "catalog"])
def test_self_pinned_receipt_is_not_authority(case, mutation):
    result, origins = produce(case)
    receipt = capture.retained_document(result["receipt"])
    if mutation in {"proposal", "catalog"}:
        receipt[mutation] = origins["proposal"]
    elif mutation == "write_audit":
        receipt[mutation]["writes"].append(str(case[0] / "outside"))
    elif mutation.endswith("_invocations"):
        receipt[mutation] = 1
    else:
        receipt[mutation] = {}
    forged = prior.put(case[0] / "custody", "forged-receipt.json", receipt)
    assert custody.validate_custody(forged, origins, case[3],
                                    reservation=result["reservation"])["status"] == "REJECTED"


def test_output_origin_and_self_pin_rejected(case):
    result, origins = produce(case)
    attempt = case[0] / "second-custody"
    reservation = capture.reserve_authentication_attempt(attempt)
    output_origins = {**origins, "proposal": result["proposal"]}
    rejected = custody.emit_custody(output_origins, case[3], attempt, reservation)
    assert rejected["status"] == "REJECTED" and "outputs are not origins" in rejected["reason"]
    assert custody.validate_custody(result["receipt"], origins, case[3])["status"] == "REJECTED"


def test_input_cannot_originate_inside_output_attempt(case):
    origins = origins_for(case)
    origins["proposal"]["path"] = str(case[0] / "custody/diagnostic_proposal.json")
    result, _ = produce(case, origins)
    assert result["status"] == "REJECTED" and "conflated" in result["reason"]


def test_write_confinement_freshness_and_preservation(case):
    attempt = case[0] / "custody"
    reservation = capture.reserve_authentication_attempt(attempt)
    with pytest.raises(FileExistsError):
        capture.reserve_authentication_attempt(attempt)
    with pytest.raises(RuntimeError, match="outside-attempt"):
        capture.verify_write_audit(
            {"attempt": str(attempt), "writes": [str(case[0] / "outside")]}, reservation)
    pin = prior.put(attempt, custody.MEMBERS[0], b"existing bytes must survive")
    with pytest.raises(RuntimeError, match="already exist"):
        custody.emit_custody(origins_for(case), case[3], attempt, reservation)
    assert capture.binding(Path(pin["path"])) == pin


def retained_validation(attempt):
    positive = prior._retained_capture_validation(attempt)
    prior.put(attempt, "retained.command-environment.json", {
        "launch": positive["identity"], "commands": positive["run_expectation"]})
    prior.put(attempt, "retained.source-role.receipt.json", {
        "roles": positive["source_roles"], "snapshots": positive["generation_snapshots"],
        "review_links": positive["review"], "latest": positive["latest"]})
    run = capture.retained_document(positive["run"])
    rows = [row for row in run["results"] if row["label"] == "check"]
    if len(rows) != 1:
        raise capture.UnavailableBinding("missing retained check payload in 92c capture receipt")
    payload_pin = rows[0]["files"][3]
    review_pin = positive["review"]["review"]
    historical = {}
    for name, pin, field in (("proposal", payload_pin, "diagnostic_identity"),
                             ("catalog", review_pin, "terminal_catalog")):
        document = capture.retained_document(pin)
        try:
            gate._at(document, [field], pin["path"])
        except capture.UnavailableBinding as error:
            receipt = {"status": "UNKNOWN", "origin": pin, "field": field,
                       "unavailable_binding": str(error), "reconstructed": False}
        else:
            raise RuntimeError(f"historical fixture unexpectedly contains {field}")
        historical[name] = prior.put(attempt, f"retained.{name}.receipt.json", receipt)
    synthetic = list((attempt / "pytest-tmp").glob(
        "test_emits_schema_one[0-9]*/custody/custody-receipt.json"))
    if len(synthetic) != 1:
        raise RuntimeError("expected one retained synthetic positive custody receipt")
    prior.put(attempt, "proposal-catalog.receipts.json", {
        "synthetic_custody": capture.binding(synthetic[0]), "historical": historical,
        "independent_review": "REQUIRED", "authority_root": False})
    prior.put(attempt, "retained-integration.results.json", {
        "status": "PASS", "capture_authenticated": True,
        "historical_identity_status": "UNKNOWN", "historical_catalog_status": "UNKNOWN",
        "historical_capture": positive["capture"], "historical_run": positive["run"],
        "reclassification_performed": False, "scientific_or_admission_claim": False})


def stage11_retained_validation(attempt, *, declaration_files=()):
    positive = prior._retained_capture_validation(attempt)
    prior.put(attempt, "stage11.source-role.receipt.json", {
        "retained_transport_fixture": positive["source_roles"],
        "generation_snapshots": positive["generation_snapshots"],
        "review_links": positive["review"], "latest": positive["latest"],
        "stage11_source_roles": "require independently trusted proposal declaration"})
    prior.put(attempt, "stage11.command-environment.receipt.json", {
        "retained_transport_fixture": positive["identity"],
        "retained_commands": positive["run_expectation"],
        "validation_argv": capture.binding(attempt / "validation.argv.json"),
        "validation_environment": capture.binding(attempt / "validation.environment.json"),
        "stage11_launch": "not inferred from validation or historical transport"})
    if not declaration_files:
        unavailable = (
            "missing independently trusted creation-time schema-1 proposal declaration "
            "byte pin for the middle-pair stage11 attention-output suffix lane")
        decision = {
            "status": "UNKNOWN", "unavailable_binding": unavailable,
            "identity_preflight_invoked": False, "dispatch_authorized": False,
            "scientific_invocations": 0, "producer_invocations": 0, "service_invocations": 0,
            "authority_root": False, "scientific_or_admission_claim": False,
            "normal_independent_review": "REQUIRED",
        }
        for member in ("proposal", "catalog", "custody", "bundle", "decision"):
            prior.put(attempt, f"stage11.{member}.receipt.json",
                      {**decision, "member": member, "authority_document_emitted": False})
        raise capture.UnavailableBinding(unavailable)

    manifest_pin, launch_pin = [capture.binding(Path(path).absolute()) for path in declaration_files]
    previous.bundle._outside_inputs(attempt, manifest_pin, launch_pin)
    origins, launch = (capture.retained_document(pin) for pin in (manifest_pin, launch_pin))
    previous.bundle._outside_inputs(attempt, origins, launch)
    prior.put(attempt, "stage11.declaration-inputs.receipt.json", {
        "caller_supplied_origins": origins, "manifest": manifest_pin, "launch": launch_pin,
        "independent_origin_trust": "caller and normal Reviewer responsibility"})
    custody_attempt, bundle_attempt = attempt / "custody", attempt / "authority-bundle"
    custody_reservation = capture.reserve_authentication_attempt(custody_attempt)
    emitted = custody.emit_custody(origins, launch, custody_attempt, custody_reservation)
    bundle_origins = custody.authority_bundle_origins(
        emitted["receipt"], origins, launch, reservation=custody_reservation)
    bundle_reservation = capture.reserve_authentication_attempt(bundle_attempt)
    materialized = previous.bundle.materialize(
        bundle_origins, launch, bundle_attempt, bundle_reservation)
    independent_origins = custody.authority_bundle_origins(
        emitted["receipt"], origins, launch, reservation=custody_reservation)
    checked = previous.bundle.validate_bundle(
        materialized["receipt"], independent_origins, launch, reservation=bundle_reservation)
    prior.put(attempt, "stage11.decision.receipt.json", {
        "custody": emitted["receipt"], "bundle": materialized["receipt"], "decision": checked,
        "service_invocations": 0, "scientific_or_admission_claim": False})
    if checked["status"] == "UNKNOWN":
        raise capture.UnavailableBinding(checked["unavailable_binding"])
    if checked["status"] != "PASS":
        raise RuntimeError(f"stage11 authority bundle rejected: {checked.get('reason')}")


def test_stage11_missing_authority_retains_every_non_emission_receipt(case, monkeypatch):
    attempt = case[0] / "missing-stage11-authority"
    attempt.mkdir()
    prior.put(attempt, "validation.argv.json", [])
    prior.put(attempt, "validation.environment.json", {})
    monkeypatch.setattr(prior, "_retained_capture_validation", lambda directory: {
        "source_roles": case[1]["source_roles"], "generation_snapshots": [],
        "review": {}, "latest": {}, "identity": case[3], "run_expectation": {}})

    def forbidden(*args, **kwargs):
        raise AssertionError("missing authority must not read narratives or invoke identity preflight")

    monkeypatch.setattr(capture, "retained_document", forbidden)
    monkeypatch.setattr(gate, "preflight_identity", forbidden)
    with pytest.raises(capture.UnavailableBinding) as caught:
        stage11_retained_validation(attempt)
    assert str(caught.value) == (
        "missing independently trusted creation-time schema-1 proposal declaration "
        "byte pin for the middle-pair stage11 attention-output suffix lane")
    for member in ("proposal", "catalog", "custody", "bundle", "decision"):
        receipt = json.loads((attempt / f"stage11.{member}.receipt.json").read_bytes())
        assert receipt["status"] == "UNKNOWN"
        assert receipt["unavailable_binding"] == str(caught.value)
        assert receipt["member"] == member
        assert receipt["authority_document_emitted"] is False
        assert receipt["identity_preflight_invoked"] is False
        assert receipt["dispatch_authorized"] is False
        assert all(receipt[key] == 0 for key in
                   ("scientific_invocations", "producer_invocations", "service_invocations"))
    assert not (attempt / "custody").exists()
    assert not (attempt / "authority-bundle").exists()


@pytest.mark.parametrize("mutation", [
    "none", "engineer", "future", "naive_time", "backdated", "science",
    "scope", "omitted_lane", "origins", "source_path", "extra_lane_field",
    "missing_role", "missing_model", "missing_budget", "missing_access", "undeclared_current_source",
])
def test_manager_origin_authentication(tmp_path, mutation):
    directory, proposal, catalog, launch = prior.identity_fixture(tmp_path)
    lane = catalog["lanes"][0]
    source = proposal["identity"]["sources"]["operator"]
    snapshot = prior.put(directory, "generation-snapshot.py", Path(source["path"]).read_bytes())
    proposal["source_roles"]["historical_generation"] = {"source": source, "retained": snapshot}
    current = proposal["source_roles"]["current_diagnostic"]["source"]
    if mutation != "undeclared_current_source":
        proposal["identity"]["sources"]["current_diagnostic"] = current
        proposal["source_snapshots"]["current_diagnostic"] = current
    if mutation.startswith("missing_"):
        field = mutation.removeprefix("missing_")
        del launch[field]
        del proposal["launch"][field]
    review = capture.retained_document(lane["review"])
    review["created_at"] = 1577836800
    lane["review"] = prior.put(directory, "dated-review.json", review)
    if mutation == "source_path":
        proposal["source_roles"]["historical_generation"]["source"] = {
            **source, "path": proposal["source_roles"]["current_diagnostic"]["source"]["path"]}
    if mutation == "omitted_lane":
        catalog["lanes"] = []
    elif mutation == "extra_lane_field":
        lane["undeclared_scope"] = "extra"
    origins = origins_for((directory, proposal, catalog, launch))
    issuance = {
        "schema_version": 1, "kind": "manager_diagnostic_identity_issuance",
        "issuer": "manager", "proposal_id": "synthetic-current", "authority_root": True,
        "authorized_science": False, "issued_at_utc": "2021-01-01T00:00:00+00:00",
        "zero_actions": {"scientific_invocations": 0},
        "origins_manifest": prior.put(directory, "manager-origins.json", origins),
        "proposal_declaration": origins["proposal"], "terminal_declarations": origins["terminals"],
        "terminal_scope": ["synthetic-closed"],
        "actual_launch": prior.put(directory, "launch.json", launch),
    }
    if mutation == "engineer":
        issuance["issuer"] = "engineer"
    elif mutation in {"future", "naive_time", "backdated"}:
        issuance["issued_at_utc"] = {
            "future": "2023-01-01T00:00:00+00:00", "naive_time": "2021-01-01T00:00:00",
            "backdated": "2019-01-01T00:00:00+00:00"}[mutation]
    elif mutation == "science":
        issuance["authorized_science"] = True
    elif mutation == "scope":
        issuance["terminal_scope"].append("omitted-closed-lane")
    elif mutation == "origins":
        issuance["proposal_declaration"] = origins["terminals"]
    pin = prior.put(directory, "issuance.json", issuance)
    now = datetime(2022, 1, 1, tzinfo=timezone.utc)
    if mutation == "none":
        checked = custody.authenticate_manager_origins(pin, "synthetic-current", now=now)
        assert checked["origins"] == origins
    else:
        with pytest.raises(RuntimeError):
            custody.authenticate_manager_origins(pin, "synthetic-current", now=now)


def manager_origin_validation(attempt):
    """Read the fixed declarations once; do not repair a rejected authority graph."""
    proposal_id = "s11-20260916t082722z-b66b6f06369e"
    directory = capture.ROOT / ".argus/live/manager-authority" / proposal_id
    pin = {"path": str(directory / "manager-issuance.json"), "bytes": 4328,
           "sha256": "208b2adea4be3c141a2a80158e68ed687dab6dfbf9d86d1de09fa8a06b7a1178"}
    issuance = capture.retained_document(pin)
    roots = {key: issuance[key] for key in (
        "proposal_declaration", "terminal_declarations", "origins_manifest", "actual_launch",
        "candidate_source", "candidate_test", "contract", "runtime_sources")}
    roots.update({key: issuance["replacement_members"][key]
                  for key in ("source_archive", "stage11", "stage13_comparator")})
    for root in roots.values():
        capture._retained_bytes(root, capture._validate_pin(root))
    prior.put(attempt, "manager-input-pins.json", {
        "issuance": pin, "members": roots, "scope": issuance["terminal_scope"],
        "validation_boundary": "current-declaration review only; no custody or identity decision"})
    original = capture.retained_document(issuance["proposal_declaration"])
    terminals = capture.retained_document(issuance["terminal_declarations"])
    prior.put(attempt, "generation-origin-comparison.json", {
        "declared": original["source_roles"]["historical_generation"],
        "retained_generations": [
            lane["capture"]["preflight"]["sources"]
            + lane["capture"]["preflight"].get("capture_implementation", [])
            for lane in terminals["lanes"]]})
    try:
        checked = custody.validate_manager_declarations(pin, proposal_id)
    except (RuntimeError, KeyError, TypeError, ValueError) as error:
        prior.put(attempt, "manager-declaration-validation.json", {
            "status": "UNKNOWN" if isinstance(error, capture.UnavailableBinding) else "FAIL",
            "issuance": pin, "members": roots, "boundary": str(error),
            "dispatch_authorized": False, "normal_independent_review": "REQUIRED"})
        raise
    prior.put(attempt, "manager-declaration-validation.json", {"status": "PASS", **checked})


def current_declaration_fixture(tmp_path, *, empty_checkpoint=False):
    """Synthetic originals, not recaptured or rewritten Manager evidence."""
    directory, proposal, catalog, launch = prior.identity_fixture(tmp_path)
    old_lane = catalog["lanes"][0]
    mission = old_lane["mission_id"]
    source = prior.put(directory, "stage13-source.py",
                       f"NAME = 'synthetic-stage13'\nBOUNDARY = {gate.STAGE13_BOUNDARY!r}\n".encode())
    source_test = prior.put(directory, "stage13-test.py", b"# synthetic test snapshot\n")
    sources = {"historical_diagnostic": source, "historical_tests": source_test}
    snapshot = prior.put(directory, "stage13-snapshot.py", Path(source["path"]).read_bytes())
    proposal["source_roles"]["historical_generation"] = {"source": source, "retained": snapshot}
    current = proposal["source_roles"]["current_diagnostic"]["source"]
    proposal["identity"]["sources"]["current_diagnostic"] = current
    proposal["source_snapshots"]["current_diagnostic"] = current
    controls = [f"control-{i}" for i in range(9)]
    words = np.arange(896, dtype="<u2")
    archive_bytes = BytesIO()
    np.savez(archive_bytes, stage13=words, stage11=words + 1)
    archive = prior.put(directory, "reference.npz", archive_bytes.getvalue())
    member = prior.put(directory, "stage13.raw", words.tobytes())
    references = {
        "original_input_L23_fp16": archive,
        "original_input_L23_binary64": prior.put(directory, "layer64.bin", b"original layer64"),
        "original_input_final_fp16": prior.put(directory, "final16.bin", b"original final16"),
        "original_input_final_binary64": prior.put(directory, "final64.bin", b"original final64"),
    }
    run_directory = directory / "legacy-run"
    run_directory.mkdir()
    argv = ["/synthetic/python", "-B", "-m", "synthetic.stage13", "--check"]
    environment = {"B": "two", "A": "one"}
    command = capture.environment_command(environment, argv)
    counts = {"final_norms": 9, "forbidden_calls": 0, "local_oracles": 45,
              "pair_heads": 9, "projections": 27, "s18_adds": 9}
    identity = {
        "diagnostic": "synthetic-stage13",
        "observation": {
            "hypothesis": "Full original-input FP16 stage13 replacement sufficiency was tested and terminated.",
            "layer": 23, "pair": [34319, 13], "position": 0,
            "replacement_stage": 13, "replacement_width": 896},
        "inputs": {**{control: archive for control in controls}, "replacement_stage13": member},
        "references": references, "sources": sources,
        "command_semantics": {"argv": argv, "command": command,
                              "mode": "retained-executed-full-vector-suffix",
                              "stages": [14, 15, 16, 17, 18, "final_rmsnorm", "selected_tied_head"]},
        "permitted_invocations": counts,
        "output_accounts": {"controls": 9, "pair": [34319, 13], "rows": 18, "stage_reports": 45,
                            "replacement": {"bytes": 1792, "encoding": gate.MEMBER_ENCODING,
                                            "input": "replacement_stage13", "member": "stage13"}},
        "termination": {"lane_terminated": True,
                        "condition": f"The reviewed {mission} full-stage13-vector suffix lane terminated "
                                     "after its one retained REJECTED observation."},
        "boundary": {
            "ace2_action": False, "closed_lanes_remain_closed": True, "cpu_only": True,
            "full_model_admission": False, "hardware_or_gpu": False, "historical_failures_preserved": True,
            "new_token_admission": False, "non_admission": True,
            "original_input_global_references_unchanged": True,
            "profile": {"kv": "FP16", "nibble_order": "native-GEMM", "operator_boundaries": "FP16",
                        "qzero_plus_one": False, "residual_state": "Q24-wide-not-FP16", "scales": "FP16",
                        "stage16_rounding": "native-S16-RTZ", "weights": "G128-asymmetric-packed-INT4"},
            "strict_fp16_state_w4a16": False},
    }
    payload = {
        "diagnostic_id": identity["diagnostic"],
        "preregistration": {"pair": [34319, 13], "source_position": 0, "coordinates": list(range(896))},
        "stage13_bindings": {name: {"archive": archive, "member": "stage13", "dtype": "<u2", "shape": [896]}
                             for name in [*controls, "original_input_fp16"]},
        "outputs": {name: {"stage13": words.tolist()} for name in controls},
        "stage_reports": {name: [{"stage": i} for i in range(14, 19)] for name in controls},
        "rows": [{"control": name, "branch": branch}
                 for name in controls for branch in ("fp16", "binary64")],
        "dispatch_and_write_audit": counts, "lane_terminated": True, "status": "REJECTED",
        "L23_reference_authority": {"reference": {
            kind: references["original_input_L23_" + kind] for kind in ("fp16", "binary64")}},
        "final_reference_authority": {"reference": {
            "logits_" + kind: {**references["original_input_final_" + kind],
                              "dtype": dtype, "shape": [151936]}
            for kind, dtype in (("fp16", "<u2"), ("binary64", "<f8"))}},
        "claim_boundary": gate.STAGE13_BOUNDARY, "flags": deepcopy(gate.STAGE13_FLAGS),
        "original_thresholds": {"synthetic": "unchanged"},
    }
    preflight = {"environment": environment, "sources": list(sources.values()), "cwd": str(capture.ROOT)}
    frames = [(command + "\n").encode(), capture.encoded(argv), capture.encoded(preflight),
              capture.encoded(payload), b""]
    frames.append(b"COMMAND\n" + frames[0] + b"ENVIRONMENT\n" + frames[2] + b"\nSTDOUT\n"
                  + frames[3] + b"\nSTDERR\n\nEXIT_STATUS=0\nTIMED_OUT=False\n")
    files = [prior.put(run_directory, "check" + suffix, data)
             for suffix, data in zip(capture.SUFFIXES, frames, strict=True)]
    receipt = prior.put(run_directory, "capture.json", {
        "preflight": preflight, "sources_after": preflight["sources"], "success": True, "failure": None,
        "results": [{"label": "check", "argv": argv, "command": command, "files": files,
                     "exit_status": 0, "timed_out": False}]})
    checkpoint = prior.put(directory, "legacy-checkpoint.txt", b"" if empty_checkpoint else
                           f"{receipt['path']} {receipt['sha256']}\n".encode())
    review = prior.put(directory, "legacy-review.json", {
        "kind": "round_reviewed_handoff", "producer_role": "reviewer", "mission_id": mission,
        "created_at": 1577836800, "round": 2, "review": {"status": "done"},
        "checkpoint": {"path": checkpoint["path"]}})
    latest = prior.put(directory, "legacy-latest.json",
                       {"kind": "handoff_ref", "handoff": {"path": review["path"]}})
    event = {"type": "life.mission.completed", "item_id": mission, "status": "done", "success": True,
             "final_review_source": "reviewer", "final_review_status": "done",
             "independent_review_required": True, "context_packet": latest["path"],
             "rounds": 2, "ts": 1577836801}
    line = json.dumps(event).encode() + b"\n"
    events = prior.put(directory, "events.jsonl", b"{}\n" + line)
    excerpt = {"source_path": events["path"], "byte_offset": 3, "byte_length": len(line),
               "line_sha256": hashlib.sha256(line).hexdigest()}
    native = {**excerpt, "pin": prior.put(directory, "native-excerpt.json", {**excerpt, "event": event}),
              "mission_path": ["event", "item_id"], "status_path": ["event", "status"]}
    provenance = {
        "diagnostic": {"pin": files[3], "path": ["diagnostic_id"]},
        "observation": {"pin": files[3], "paths": [["preregistration"], ["stage13_bindings"]]},
        "inputs": {"working_archives": {"pin": files[3], "path": ["outputs"]},
                   "replacement_stage13": {"source_archive": archive, "source_member": "stage13",
                                           "derived_pin": member, "encoding": gate.MEMBER_ENCODING}},
        "references": {"pin": files[3], "paths": [["L23_reference_authority"], ["final_reference_authority"]]},
        "sources": {"pin": files[2], "path": ["sources"]},
        "command_semantics": {"receipt": receipt, "label": "check"},
        "permitted_invocations": {"pin": files[3], "path": ["dispatch_and_write_audit"]},
        "output_accounts": {"pin": files[3], "paths": [["outputs"], ["stage_reports"], ["rows"]]},
        "termination": {"pin": files[3], "paths": [["lane_terminated"], ["status"]]},
        "boundary": {"pin": files[3], "paths": [["claim_boundary"], ["flags"], ["original_thresholds"]]},
    }
    lane = {"mission_id": mission, "latest": latest, "review": review, "checkpoint": checkpoint,
            "native": native, "source_snapshots": sources, "declaration_mode": gate.CURRENT_DECLARATION,
            "legacy_diagnostic_identity_embedded": False, "diagnostic_identity": identity,
            "identity_provenance": provenance, "capture": {
                "directory": str(run_directory), "receipt": receipt, "preflight": preflight,
                "commands": {"check": argv}, "label": "check"}}
    return directory, proposal, {"schema_version": 1, "lanes": [lane]}, launch


def current_authority(case, *, with_review=True, issuer="manager", issued="2021-01-01T00:00:00+00:00"):
    directory, _, catalog, launch = case
    lane = catalog["lanes"][0]
    origins = origins_for(case)
    issuance = {
        "schema_version": 1, "kind": "manager_diagnostic_identity_issuance", "issuer": issuer,
        "proposal_id": "synthetic-current", "authority_root": True, "authorized_science": False,
        "issued_at_utc": issued, "zero_actions": {"scientific_invocations": 0},
        "origins_manifest": prior.put(directory, "origins.json", origins),
        "proposal_declaration": origins["proposal"], "terminal_declarations": origins["terminals"],
        "terminal_scope": [lane["mission_id"]], "actual_launch": prior.put(directory, "actual-launch.json", launch)}
    pin = prior.put(directory, "manager-issuance.json", issuance)
    authority = {"issuance": pin, "proposal_id": "synthetic-current"}
    if with_review:
        links = [pin, *origins.values(), lane["latest"], lane["review"], lane["checkpoint"],
                 lane["native"]["pin"], lane["capture"]["receipt"], *lane["source_snapshots"].values()]
        checkpoint = prior.put(directory, "current-checkpoint.txt",
                               "".join(f"{p['path']} {p['sha256']}\n" for p in links).encode())
        review = prior.put(directory, "current-review.json", {
            "kind": "round_reviewed_handoff", "producer_role": "reviewer", "mission_id": "current-review",
            "created_at": 1640995200, "review": {"status": "done"},
            "checkpoint": {"path": checkpoint["path"]}})
        latest = prior.put(directory, "current-latest.json",
                           {"kind": "handoff_ref", "handoff": {"path": review["path"]}})
        authority["review"] = {"latest": latest, "review": review, "checkpoint": checkpoint,
                               "mission_id": "current-review"}
    return authority


@pytest.mark.parametrize("mode", ["reviewed", "pending", "empty_reviewed", "empty_pending", "unreviewed"])
def test_current_declaration_positive_and_review_gate(tmp_path, mode):
    case = current_declaration_fixture(tmp_path, empty_checkpoint=mode.startswith("empty"))
    authority = current_authority(case, with_review=mode in {"reviewed", "empty_reviewed"})
    lane = case[2]["lanes"][0]
    if mode in {"empty_pending", "unreviewed"}:
        with pytest.raises(capture.UnavailableBinding, match="separate current reviewed"):
            gate._closed_lane(lane, manager_authority=authority, review_pending=mode == "empty_pending")
    else:
        checked = gate._closed_lane(lane, manager_authority=authority, review_pending=mode == "pending")
        assert checked["diagnostic"] == "synthetic-stage13"
        assert checked["inputs"]["replacement_stage13"]["bytes"] == 1792
        if mode == "empty_reviewed":
            assert Path(lane["checkpoint"]["path"]).read_bytes() == b""


@pytest.mark.parametrize("field", sorted(gate.FIELDS))
def test_current_declaration_field_provenance_fails_closed(tmp_path, field):
    case = current_declaration_fixture(tmp_path)
    lane = case[2]["lanes"][0]
    lane["identity_provenance"][field] = {"narrative": "hashes match, accepted"}
    authority = current_authority(case)
    with pytest.raises((RuntimeError, KeyError)):
        gate._closed_lane(lane, manager_authority=authority)


@pytest.mark.parametrize("field", sorted(gate.FIELDS))
def test_current_declaration_identity_values_fail_closed(tmp_path, field):
    case = current_declaration_fixture(tmp_path)
    case[2]["lanes"][0]["diagnostic_identity"][field] = {"changed": True}
    authority = current_authority(case)
    with pytest.raises((RuntimeError, KeyError)):
        gate._closed_lane(case[2]["lanes"][0], manager_authority=authority)


@pytest.mark.parametrize("mutation", [
    "none", "environment_order", "environment_value", "duplicate_assignment", "argv", "stages",
    "swapped_final_references", "wrong_final_member", "hash_only_final_reference",
])
def test_current_declaration_named_reference_and_command_semantics(tmp_path, mutation):
    case = current_declaration_fixture(tmp_path)
    lane = case[2]["lanes"][0]
    identity = lane["diagnostic_identity"]
    command = identity["command_semantics"]
    if mutation == "environment_order":
        environment = lane["capture"]["preflight"]["environment"]
        command["command"] = capture.environment_command(
            dict(reversed(list(environment.items()))), command["argv"])
    elif mutation == "environment_value":
        command["command"] = command["command"].replace("B=two", "B=changed")
    elif mutation == "duplicate_assignment":
        command["command"] = "A=one " + command["command"]
    elif mutation == "argv":
        command["argv"] = [*command["argv"], "--changed"]
    elif mutation == "stages":
        command["stages"] = [13, *command["stages"]]
    elif mutation == "swapped_final_references":
        refs = identity["references"]
        refs["original_input_final_fp16"], refs["original_input_final_binary64"] = (
            refs["original_input_final_binary64"], refs["original_input_final_fp16"])
    elif mutation == "wrong_final_member":
        identity["references"]["original_input_final_fp16"] = identity["references"]["original_input_L23_fp16"]
    elif mutation == "hash_only_final_reference":
        del identity["references"]["original_input_final_fp16"]["path"]
    authority = current_authority(case)
    if mutation in {"none", "environment_order"}:
        checked = gate._closed_lane(lane, manager_authority=authority)
        assert checked["command_semantics"]["command"].startswith("A=one B=two ")
        assert checked["references"]["original_input_final_fp16"]["sha256"] == (
            identity["references"]["original_input_final_fp16"]["sha256"])
    else:
        with pytest.raises(RuntimeError):
            gate._closed_lane(lane, manager_authority=authority)


@pytest.mark.parametrize("mutation", [
    "engineer", "backdate", "future", "self_pin", "scope", "omitted_lane", "source_origin",
    "event_offset", "event_length", "event_hash", "event_bytes", "event_member", "snapshot",
    "stdout", "environment", "argv", "framing", "receipt_member", "replacement", "archive",
    "review_role", "review_time", "review_receipt", "latest", "embedded_claim",
])
def test_current_declaration_binding_mutations_fail_closed(tmp_path, mutation):
    case = current_declaration_fixture(tmp_path)
    lane = case[2]["lanes"][0]
    if mutation in {"event_offset", "event_length", "event_hash"}:
        key = {"event_offset": "byte_offset", "event_length": "byte_length", "event_hash": "line_sha256"}[mutation]
        lane["native"][key] = "0" * 64 if mutation == "event_hash" else lane["native"][key] + 1
    elif mutation == "source_origin":
        case[1]["source_roles"]["historical_generation"]["source"] = {
            **lane["diagnostic_identity"]["sources"]["historical_diagnostic"],
            "path": case[1]["source_roles"]["current_diagnostic"]["source"]["path"]}
    elif mutation == "embedded_claim":
        lane["legacy_diagnostic_identity_embedded"] = True
    authority = current_authority(
        case, issuer="engineer" if mutation == "engineer" else "manager",
        issued={"backdate": "2019-01-01T00:00:00+00:00",
                "future": "2999-01-01T00:00:00+00:00"}.get(mutation, "2021-01-01T00:00:00+00:00"))
    if mutation == "self_pin":
        authority["issuance"] = lane["capture"]["receipt"]
    elif mutation in {"scope", "omitted_lane"}:
        issuance = capture.retained_document(authority["issuance"])
        if mutation == "scope":
            issuance["terminal_scope"].append("omitted-closed")
        else:
            issuance["terminal_scope"] = []
        authority["issuance"] = prior.put(tmp_path, "changed-issuance.json", issuance)
    elif mutation in {"event_bytes", "event_member", "snapshot", "replacement", "archive", "latest"}:
        path = {
            "event_bytes": lane["native"]["source_path"],
            "event_member": lane["native"]["pin"]["path"],
            "snapshot": lane["source_snapshots"]["historical_tests"]["path"],
            "replacement": lane["diagnostic_identity"]["inputs"]["replacement_stage13"]["path"],
            "archive": lane["identity_provenance"]["inputs"]["replacement_stage13"]["source_archive"]["path"],
            "latest": lane["latest"]["path"],
        }[mutation]
        Path(path).write_bytes(b"changed")
    elif mutation in {"stdout", "environment", "argv", "framing", "receipt_member"}:
        receipt = capture.retained_document(lane["capture"]["receipt"])
        if mutation == "receipt_member":
            receipt["results"][0]["files"][3] = receipt["results"][0]["files"][4]
            Path(lane["capture"]["receipt"]["path"]).write_bytes(capture.encoded(receipt))
        else:
            index = {"stdout": 3, "environment": 2, "argv": 1, "framing": 5}[mutation]
            Path(receipt["results"][0]["files"][index]["path"]).write_bytes(b"changed")
    elif mutation in {"review_role", "review_time"}:
        review = capture.retained_document(authority["review"]["review"])
        review["producer_role" if mutation == "review_role" else "created_at"] = (
            "engineer" if mutation == "review_role" else 0)
        authority["review"]["review"] = prior.put(tmp_path, "bad-current-review.json", review)
        authority["review"]["latest"] = prior.put(tmp_path, "bad-current-latest.json",
            {"kind": "handoff_ref", "handoff": {"path": authority["review"]["review"]["path"]}})
    elif mutation == "review_receipt":
        Path(authority["review"]["checkpoint"]["path"]).write_bytes(b"hash-only narrative")
    with pytest.raises((RuntimeError, KeyError)):
        gate._closed_lane(lane, manager_authority=authority)


@pytest.mark.parametrize("mutation", [
    "none", "environment_order", "missing", "extra", "argv", "environment_value", "duplicate_assignment",
])
def test_current_declaration_command_map_and_framing(tmp_path, mutation):
    case = prior.identity_fixture(tmp_path)
    lane = case[2]["lanes"][0]
    old = capture.retained_document(lane["capture"]["receipt"])
    directory = tmp_path / "ordered-capture"
    directory.mkdir()
    receipt = {key: deepcopy(value) for key, value in old.items() if key != "results"}
    receipt["results"] = []
    commands = {}
    for label in ("z-first", "a-last"):
        row = deepcopy(old["results"][0])
        row["label"] = label
        commands[label] = row["argv"]
        data = [Path(pin["path"]).read_bytes() for pin in row["files"]]
        if mutation in {"environment_order", "duplicate_assignment"}:
            environment = receipt["preflight"]["environment"]
            row["command"] = capture.environment_command(
                dict(reversed(list(environment.items()))), row["argv"])
            if mutation == "duplicate_assignment":
                row["command"] = "A=one " + row["command"]
            data[0] = (row["command"] + "\n").encode()
        if mutation == "environment_value":
            altered = capture.decode_retained(data[2])
            altered["environment"]["A"] = "changed"
            data[2] = capture.encoded(altered)
        data[5] = (b"COMMAND\n" + data[0] + b"ENVIRONMENT\n" + data[2] + b"\nSTDOUT\n"
                   + data[3] + b"\nSTDERR\n" + data[4] + b"\nEXIT_STATUS=0\nTIMED_OUT=False\n")
        row["files"] = [prior.put(directory, label + suffix, value)
                        for suffix, value in zip(capture.SUFFIXES, data, strict=True)]
        receipt["results"].append(row)
    commands = dict(sorted(commands.items()))
    if mutation == "missing":
        del commands["z-first"]
    elif mutation == "extra":
        commands["unexpected"] = commands["z-first"]
    elif mutation == "argv":
        commands["z-first"] = commands["z-first"] + ["--changed"]
    run = {"directory": str(directory), "receipt": prior.put(directory, "capture.json", receipt),
           "preflight": receipt["preflight"], "commands": commands}
    if mutation in {"none", "environment_order"}:
        assert [row["label"] for row in gate._retained_run(run)["results"]] == ["z-first", "a-last"]
    else:
        with pytest.raises(RuntimeError):
            gate._retained_run(run)


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] in (
            "--validate-manager-origins", "--validate-manager-declarations"):
        here = Path(__file__).resolve()
        sources = (Path(previous.bundle.__file__).resolve(), Path(custody.__file__).resolve(),
                   Path(previous.__file__).resolve(), here)
        forbidden = (
            (str(Path(custody.__file__).resolve()), "emit_custody", "custody_invocations"),
            (str(Path(previous.bundle.__file__).resolve()), "materialize", "materialize_invocations"),
            (str(Path(gate.__file__).resolve()), "preflight_identity", "preflight_invocations"),
        )
        outcome = prior.validate(
            Path(sys.argv[2]).absolute(), retained_validation=manager_origin_validation,
            extra_sources=sources, forbidden_functions=forbidden,
            test_paths=(
                str(here) + "::test_manager_origin_authentication",
                str(here) + "::test_current_declaration_positive_and_review_gate",
                str(here) + "::test_current_declaration_field_provenance_fails_closed",
                str(here) + "::test_current_declaration_identity_values_fail_closed",
                str(here) + "::test_current_declaration_named_reference_and_command_semantics",
                str(here) + "::test_current_declaration_binding_mutations_fail_closed",
                str(here) + "::test_current_declaration_command_map_and_framing",
                str(Path(prior.__file__).resolve()) + "::test_generation_origin_requires_original_pin",
                str(Path(prior.__file__).resolve()) + "::test_current_declaration_stage_member",
                str(Path(prior.__file__).resolve()) + "::test_current_declaration_preserves_embedded_mode"))
        print(json.dumps({key: value for key, value in outcome.items() if key != "members"},
                         sort_keys=True))
        print((Path(sys.argv[2]) / "validation.stdout").read_text()[-1000:])
        raise SystemExit(outcome["exit_status"])
    if (len(sys.argv) not in (3, 5)
            or sys.argv[1] not in ("--validate", "--validate-stage11")
            or (sys.argv[1] == "--validate" and len(sys.argv) != 3)):
        raise SystemExit(
            "expected --validate FRESH_IGNORED_ATTEMPT or "
            "--validate-stage11 FRESH_IGNORED_ATTEMPT [TRUSTED_DECLARATION_PINS ACTUAL_LAUNCH]")
    callback = retained_validation
    if sys.argv[1] == "--validate-stage11":
        def callback(attempt):
            stage11_retained_validation(attempt, declaration_files=sys.argv[3:])
    outcome = prior.validate(
        Path(sys.argv[2]).absolute(), retained_validation=callback,
        extra_sources=(Path(previous.bundle.__file__).resolve(), Path(custody.__file__).resolve(),
                       Path(previous.__file__).resolve(), Path(__file__).resolve()),
        test_paths=(Path(prior.__file__).resolve(), Path(previous.__file__).resolve(),
                    Path(__file__).resolve()))
    print(json.dumps({key: value for key, value in outcome.items() if key != "members"}, sort_keys=True))
    raise SystemExit(outcome["exit_status"])
